[workspace]
    members  = [
        "common",
        "domain",
        "day1",
        "day4",
        "day5",
        "day6",
        "day7",
        "utilities",
        "server",
        "minus1",
    ]

resolver = "2"