[workspace]
    members = [
        "binary",
        "domain",
        "errors",
        "minus1",
        "day1",
        "day4",
        "day5",
        "day6",
        "day7",
        "utilities",
    ]

resolver = "2"